spring:
    application:
        name: resilience-jpa
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5455/resilience-jpa
        username: postgres
        password: postgres
        hikari:
            pool-name: ConnPool
            connection-timeout: 5000 # maximum number of milliseconds that a client will wait for a connection # default : 30s
            maximum-pool-size: 2 # maximum pool size
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        properties:
            jakarta:
                persistence:
                    query:
                        timeout: 15000
    hibernate:
        ddl-auto: true
    show-sql: true

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false

management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true

resilience4j:
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
        instances:
            jpa:
                sliding-window-size: 100
                sliding-window-type: COUNT_BASED
#                sliding-window-type: TIME_BASED
                failure-rate-threshold: 50
                wait-duration-in-open-state: 30s
                minimum-number-of-calls: 1000
                automatic-transition-from-open-to-half-open-enabled: true
                permitted-number-of-calls-in-half-open-state: 3


logging.level.com.zaxxer.hikari.HikariConfig: DEBUG
logging.level.com.zaxxer.hikari: TRACE
logging.level.com.example.resiliencejpa: TRACE